### PR TITLE
Set the DNS Service name to `kube-dns` for `net-exporter`

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/roadmap/issues/725

### CODE REVIEW

**Comment by erkanerol** [comment]
@kopiczko why do we use the test catalog here? is it for only testing this PR?

**Comment by kopiczko** [comment]
> @kopiczko why do we use the test catalog here? is it for only testing this PR?

I use it for testing.

**Review by erkanerol — APPROVED** [review]

**Comment by erkanerol** [comment]
Requires rebase after https://github.com/giantswarm/default-apps-openstack/pull/16

**Comment by kopiczko** [comment]
Replaced with https://github.com/giantswarm/default-apps-openstack/pull/26

**Pull request closed without merging**
